# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEHm6UjZ59ezkCOYKkJErP0ztIuzm-B6
"""

pip install beautifulsoup4

pip install user_agent

pip install pyTelegramBotApi

import telebot
import random
import requests
from bs4 import BeautifulSoup
import re
from user_agent import generate_user_agent

token='1030911728:AAG9f8OdE8ysuz8iamm8rdbfG62cuos28Es'
bot=telebot.TeleBot(token)
url='';
mas=[]
@bot.message_handler(content_types=['text'])
def start(message):
    if message.text == '/start':
        bot.send_message(message.from_user.id, "Привет. Напиши ссылку для парсинга");
        bot.register_next_step_handler(message, get_url); #следующий шаг – функция get_url
    else:
        bot.send_message(message.from_user.id, 'Напиши /start');

def get_url(message):
  url = message.text
  
# generate a user agent
  headers = {'User-Agent': generate_user_agent(device_type="desktop", os=('mac', 'linux'))}

  page_response = requests.get(url, timeout=5, headers=headers)
  soup=BeautifulSoup(page_response.content, 'html.parser')
  src=re.compile('^\/context\/detail\/id\/\d{2,}\/$')
  for link in soup.find_all('a'):
    if link.get('href') and re.search(src,link.get('href')): # Проверка,что строка не NoneType,затем что она входит в нашу маску поиска
        mas.append(link.get('href'))
    else:
        pass
    
  product1='www.ozon.ru'+random.choice(mas)
  product2='www.ozon.ru'+random.choice(mas)
  bot.send_message(message.from_user.id, "Я думаю,тебе нужно вот это")
  bot.send_message(message.from_user.id, product1)
  bot.send_message(message.from_user.id, product2)



  
bot.polling()